// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Template Package",
    platforms: [
        .macOS("15.0"),
        .iOS("18.0"),
        .tvOS("18.0"),
        .watchOS("11.0"),
        .macCatalyst("18.0")
    ],
    products: [
        .library(
            name: "Template",
            targets: ["Template"]
        ),
        .iOSApplication(
            name: "Template Package",
            targets: ["Template_App"],
            teamIdentifier: "VKFDYMU9HJ",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .leaf),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .target(
            name: "Template",
            path: "Template"
        ),
        .executableTarget(
            name: "Template_App",
            dependencies: [
                "Template"
            ],
            path: "Template_App"
        )
    ],
    swiftLanguageVersions: [.version("6")]
)
